// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckProgress():Promise<number>;

export function GetHeaders(arg1:Array<Record<string, any>>):Promise<Array<string>>;

export function GetSaves():Promise<Array<Record<string, any>>>;

export function StartQuickScan():Promise<void>;

export function StartScan():Promise<void>;
