// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckProgress() {
  return window['go']['main']['App']['CheckProgress']();
}

export function StartScan() {
  return window['go']['main']['App']['StartScan']();
}
