// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package main

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// __createSavesInput is used internally by genqlient
type __createSavesInput struct {
	Device      string   `json:"device"`
	Console     string   `json:"console"`
	Directories []string `json:"directories"`
	Timemod     []int    `json:"timemod"`
}

// GetDevice returns __createSavesInput.Device, and is useful for accessing the field via an interface.
func (v *__createSavesInput) GetDevice() string { return v.Device }

// GetConsole returns __createSavesInput.Console, and is useful for accessing the field via an interface.
func (v *__createSavesInput) GetConsole() string { return v.Console }

// GetDirectories returns __createSavesInput.Directories, and is useful for accessing the field via an interface.
func (v *__createSavesInput) GetDirectories() []string { return v.Directories }

// GetTimemod returns __createSavesInput.Timemod, and is useful for accessing the field via an interface.
func (v *__createSavesInput) GetTimemod() []int { return v.Timemod }

// __deleteLocalInput is used internally by genqlient
type __deleteLocalInput struct {
	Device string `json:"device"`
}

// GetDevice returns __deleteLocalInput.Device, and is useful for accessing the field via an interface.
func (v *__deleteLocalInput) GetDevice() string { return v.Device }

// createSavesCreateSavesPost includes the requested fields of the GraphQL type Post.
type createSavesCreateSavesPost struct {
	Device      string   `json:"Device"`
	Console     string   `json:"Console"`
	Directories []string `json:"Directories"`
	Timemod     []int    `json:"Timemod"`
}

// GetDevice returns createSavesCreateSavesPost.Device, and is useful for accessing the field via an interface.
func (v *createSavesCreateSavesPost) GetDevice() string { return v.Device }

// GetConsole returns createSavesCreateSavesPost.Console, and is useful for accessing the field via an interface.
func (v *createSavesCreateSavesPost) GetConsole() string { return v.Console }

// GetDirectories returns createSavesCreateSavesPost.Directories, and is useful for accessing the field via an interface.
func (v *createSavesCreateSavesPost) GetDirectories() []string { return v.Directories }

// GetTimemod returns createSavesCreateSavesPost.Timemod, and is useful for accessing the field via an interface.
func (v *createSavesCreateSavesPost) GetTimemod() []int { return v.Timemod }

// createSavesResponse is returned by createSaves on success.
type createSavesResponse struct {
	CreateSaves createSavesCreateSavesPost `json:"createSaves"`
}

// GetCreateSaves returns createSavesResponse.CreateSaves, and is useful for accessing the field via an interface.
func (v *createSavesResponse) GetCreateSaves() createSavesCreateSavesPost { return v.CreateSaves }

// deleteLocalDeleteLocalDeviceName includes the requested fields of the GraphQL type DeviceName.
type deleteLocalDeleteLocalDeviceName struct {
	Device string `json:"Device"`
}

// GetDevice returns deleteLocalDeleteLocalDeviceName.Device, and is useful for accessing the field via an interface.
func (v *deleteLocalDeleteLocalDeviceName) GetDevice() string { return v.Device }

// deleteLocalResponse is returned by deleteLocal on success.
type deleteLocalResponse struct {
	DeleteLocal deleteLocalDeleteLocalDeviceName `json:"deleteLocal"`
}

// GetDeleteLocal returns deleteLocalResponse.DeleteLocal, and is useful for accessing the field via an interface.
func (v *deleteLocalResponse) GetDeleteLocal() deleteLocalDeleteLocalDeviceName { return v.DeleteLocal }

// The mutation executed by createSaves.
const createSaves_Operation = `
mutation createSaves ($device: String!, $console: String!, $directories: [String!], $timemod: [Int!]) {
	createSaves(input: {Device:$device,Console:$console,Directories:$directories,Timemod:$timemod}) {
		Device
		Console
		Directories
		Timemod
	}
}
`

func createSaves(
	ctx_ context.Context,
	client_ graphql.Client,
	device string,
	console string,
	directories []string,
	timemod []int,
) (data_ *createSavesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "createSaves",
		Query:  createSaves_Operation,
		Variables: &__createSavesInput{
			Device:      device,
			Console:     console,
			Directories: directories,
			Timemod:     timemod,
		},
	}

	data_ = &createSavesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by deleteLocal.
const deleteLocal_Operation = `
mutation deleteLocal ($device: String!) {
	deleteLocal(input: {Device:$device}) {
		Device
	}
}
`

func deleteLocal(
	ctx_ context.Context,
	client_ graphql.Client,
	device string,
) (data_ *deleteLocalResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "deleteLocal",
		Query:  deleteLocal_Operation,
		Variables: &__deleteLocalInput{
			Device: device,
		},
	}

	data_ = &deleteLocalResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
