// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package main

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// __createSavesInput is used internally by genqlient
type __createSavesInput struct {
	Device      string   `json:"device"`
	Console     string   `json:"console"`
	Directories []string `json:"directories"`
	Timemod     []int    `json:"timemod"`
}

// GetDevice returns __createSavesInput.Device, and is useful for accessing the field via an interface.
func (v *__createSavesInput) GetDevice() string { return v.Device }

// GetConsole returns __createSavesInput.Console, and is useful for accessing the field via an interface.
func (v *__createSavesInput) GetConsole() string { return v.Console }

// GetDirectories returns __createSavesInput.Directories, and is useful for accessing the field via an interface.
func (v *__createSavesInput) GetDirectories() []string { return v.Directories }

// GetTimemod returns __createSavesInput.Timemod, and is useful for accessing the field via an interface.
func (v *__createSavesInput) GetTimemod() []int { return v.Timemod }

// __deleteLocalIDInput is used internally by genqlient
type __deleteLocalIDInput struct {
	Id int `json:"id"`
}

// GetId returns __deleteLocalIDInput.Id, and is useful for accessing the field via an interface.
func (v *__deleteLocalIDInput) GetId() int { return v.Id }

// __deleteLocalInput is used internally by genqlient
type __deleteLocalInput struct {
	Device string `json:"device"`
}

// GetDevice returns __deleteLocalInput.Device, and is useful for accessing the field via an interface.
func (v *__deleteLocalInput) GetDevice() string { return v.Device }

// __getPathsInput is used internally by genqlient
type __getPathsInput struct {
	Device string `json:"device"`
	UserID int    `json:"userID"`
}

// GetDevice returns __getPathsInput.Device, and is useful for accessing the field via an interface.
func (v *__getPathsInput) GetDevice() string { return v.Device }

// GetUserID returns __getPathsInput.UserID, and is useful for accessing the field via an interface.
func (v *__getPathsInput) GetUserID() int { return v.UserID }

// __updateTimeInput is used internally by genqlient
type __updateTimeInput struct {
	Id      int `json:"id"`
	Timemod int `json:"timemod"`
}

// GetId returns __updateTimeInput.Id, and is useful for accessing the field via an interface.
func (v *__updateTimeInput) GetId() int { return v.Id }

// GetTimemod returns __updateTimeInput.Timemod, and is useful for accessing the field via an interface.
func (v *__updateTimeInput) GetTimemod() int { return v.Timemod }

// createSavesCreateSavesPost includes the requested fields of the GraphQL type Post.
type createSavesCreateSavesPost struct {
	Device      string   `json:"Device"`
	Console     string   `json:"Console"`
	Directories []string `json:"Directories"`
	Timemod     []int    `json:"Timemod"`
}

// GetDevice returns createSavesCreateSavesPost.Device, and is useful for accessing the field via an interface.
func (v *createSavesCreateSavesPost) GetDevice() string { return v.Device }

// GetConsole returns createSavesCreateSavesPost.Console, and is useful for accessing the field via an interface.
func (v *createSavesCreateSavesPost) GetConsole() string { return v.Console }

// GetDirectories returns createSavesCreateSavesPost.Directories, and is useful for accessing the field via an interface.
func (v *createSavesCreateSavesPost) GetDirectories() []string { return v.Directories }

// GetTimemod returns createSavesCreateSavesPost.Timemod, and is useful for accessing the field via an interface.
func (v *createSavesCreateSavesPost) GetTimemod() []int { return v.Timemod }

// createSavesResponse is returned by createSaves on success.
type createSavesResponse struct {
	CreateSaves createSavesCreateSavesPost `json:"createSaves"`
}

// GetCreateSaves returns createSavesResponse.CreateSaves, and is useful for accessing the field via an interface.
func (v *createSavesResponse) GetCreateSaves() createSavesCreateSavesPost { return v.CreateSaves }

// deleteLocalDeleteLocalDeviceName includes the requested fields of the GraphQL type DeviceName.
type deleteLocalDeleteLocalDeviceName struct {
	Device string `json:"Device"`
}

// GetDevice returns deleteLocalDeleteLocalDeviceName.Device, and is useful for accessing the field via an interface.
func (v *deleteLocalDeleteLocalDeviceName) GetDevice() string { return v.Device }

// deleteLocalIDDeleteLocalIDUseID includes the requested fields of the GraphQL type UseID.
type deleteLocalIDDeleteLocalIDUseID struct {
	ID int `json:"ID"`
}

// GetID returns deleteLocalIDDeleteLocalIDUseID.ID, and is useful for accessing the field via an interface.
func (v *deleteLocalIDDeleteLocalIDUseID) GetID() int { return v.ID }

// deleteLocalIDResponse is returned by deleteLocalID on success.
type deleteLocalIDResponse struct {
	DeleteLocalID deleteLocalIDDeleteLocalIDUseID `json:"deleteLocalID"`
}

// GetDeleteLocalID returns deleteLocalIDResponse.DeleteLocalID, and is useful for accessing the field via an interface.
func (v *deleteLocalIDResponse) GetDeleteLocalID() deleteLocalIDDeleteLocalIDUseID {
	return v.DeleteLocalID
}

// deleteLocalResponse is returned by deleteLocal on success.
type deleteLocalResponse struct {
	DeleteLocal deleteLocalDeleteLocalDeviceName `json:"deleteLocal"`
}

// GetDeleteLocal returns deleteLocalResponse.DeleteLocal, and is useful for accessing the field via an interface.
func (v *deleteLocalResponse) GetDeleteLocal() deleteLocalDeleteLocalDeviceName { return v.DeleteLocal }

// getPathsGetPaths includes the requested fields of the GraphQL type Paths.
type getPathsGetPaths struct {
	Paths []string `json:"Paths"`
	IDs   []int    `json:"IDs"`
}

// GetPaths returns getPathsGetPaths.Paths, and is useful for accessing the field via an interface.
func (v *getPathsGetPaths) GetPaths() []string { return v.Paths }

// GetIDs returns getPathsGetPaths.IDs, and is useful for accessing the field via an interface.
func (v *getPathsGetPaths) GetIDs() []int { return v.IDs }

// getPathsResponse is returned by getPaths on success.
type getPathsResponse struct {
	GetPaths getPathsGetPaths `json:"getPaths"`
}

// GetGetPaths returns getPathsResponse.GetPaths, and is useful for accessing the field via an interface.
func (v *getPathsResponse) GetGetPaths() getPathsGetPaths { return v.GetPaths }

// updateTimeResponse is returned by updateTime on success.
type updateTimeResponse struct {
	UpdateTime updateTimeUpdateTimePostTime `json:"updateTime"`
}

// GetUpdateTime returns updateTimeResponse.UpdateTime, and is useful for accessing the field via an interface.
func (v *updateTimeResponse) GetUpdateTime() updateTimeUpdateTimePostTime { return v.UpdateTime }

// updateTimeUpdateTimePostTime includes the requested fields of the GraphQL type PostTime.
type updateTimeUpdateTimePostTime struct {
	ID      int `json:"ID"`
	TimeMod int `json:"TimeMod"`
}

// GetID returns updateTimeUpdateTimePostTime.ID, and is useful for accessing the field via an interface.
func (v *updateTimeUpdateTimePostTime) GetID() int { return v.ID }

// GetTimeMod returns updateTimeUpdateTimePostTime.TimeMod, and is useful for accessing the field via an interface.
func (v *updateTimeUpdateTimePostTime) GetTimeMod() int { return v.TimeMod }

// The mutation executed by createSaves.
const createSaves_Operation = `
mutation createSaves ($device: String!, $console: String!, $directories: [String!], $timemod: [Int!]) {
	createSaves(input: {Device:$device,Console:$console,Directories:$directories,Timemod:$timemod}) {
		Device
		Console
		Directories
		Timemod
	}
}
`

func createSaves(
	ctx_ context.Context,
	client_ graphql.Client,
	device string,
	console string,
	directories []string,
	timemod []int,
) (data_ *createSavesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "createSaves",
		Query:  createSaves_Operation,
		Variables: &__createSavesInput{
			Device:      device,
			Console:     console,
			Directories: directories,
			Timemod:     timemod,
		},
	}

	data_ = &createSavesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by deleteLocal.
const deleteLocal_Operation = `
mutation deleteLocal ($device: String!) {
	deleteLocal(input: {Device:$device}) {
		Device
	}
}
`

func deleteLocal(
	ctx_ context.Context,
	client_ graphql.Client,
	device string,
) (data_ *deleteLocalResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "deleteLocal",
		Query:  deleteLocal_Operation,
		Variables: &__deleteLocalInput{
			Device: device,
		},
	}

	data_ = &deleteLocalResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by deleteLocalID.
const deleteLocalID_Operation = `
mutation deleteLocalID ($id: Int!) {
	deleteLocalID(input: {ID:$id}) {
		ID
	}
}
`

func deleteLocalID(
	ctx_ context.Context,
	client_ graphql.Client,
	id int,
) (data_ *deleteLocalIDResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "deleteLocalID",
		Query:  deleteLocalID_Operation,
		Variables: &__deleteLocalIDInput{
			Id: id,
		},
	}

	data_ = &deleteLocalIDResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by getPaths.
const getPaths_Operation = `
query getPaths ($device: String!, $userID: Int!) {
	getPaths(Device: $device, UserID: $userID) {
		Paths
		IDs
	}
}
`

func getPaths(
	ctx_ context.Context,
	client_ graphql.Client,
	device string,
	userID int,
) (data_ *getPathsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "getPaths",
		Query:  getPaths_Operation,
		Variables: &__getPathsInput{
			Device: device,
			UserID: userID,
		},
	}

	data_ = &getPathsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by updateTime.
const updateTime_Operation = `
mutation updateTime ($id: Int!, $timemod: Int!) {
	updateTime(input: {ID:$id,TimeMod:$timemod}) {
		ID
		TimeMod
	}
}
`

func updateTime(
	ctx_ context.Context,
	client_ graphql.Client,
	id int,
	timemod int,
) (data_ *updateTimeResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "updateTime",
		Query:  updateTime_Operation,
		Variables: &__updateTimeInput{
			Id:      id,
			Timemod: timemod,
		},
	}

	data_ = &updateTimeResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
